### PR TITLE
feat(5): file upload to s3 bucket

### PR DESCRIPTION
**Pull request by dartwlad**
Evaluation criteria:
Everything is working.
https://d2igrds53f0okp.cloudfront.net/admin/products
FE PRs:
https://github.com/dartwlad/nodejs-aws-fe/pull/5
https://github.com/dartwlad/nodejs-aws-fe/pull/6
Additional (optional) tasks
+1 - async/await is used in lambda functions
+1 - importProductsFile lambda is covered by unit tests 
+1 - At the end of the stream the lambda function should move the file from the uploaded folder into the parsed folder (move the file means that file should be copied into parsed folder, and then deleted from uploaded folder)

### CODE REVIEW

**Comment by BaturevichNikita** [comment]
image
Upload CSV file to s3 doesn't work. 403 error. Pls, fix cors.

**Comment by dartwlad** [comment]
> image
> Upload CSV file to s3 doesn't work. 403 error. Pls, fix cors.

Thank you for the comment.
Could you please provide more details on how to reproduce this issue?
From my perspective upload is working.
image

**Comment by BaturevichNikita** [comment]
I just can't upload any .csv file =)

**Comment by dartwlad** [comment]
> I just can't upload any .csv file =)

please provide your csv file

**Comment by dartwlad** [comment]
@BaturevichNikita @trigolos
please review updated solution.
the issue was in the file type. windows and Linux setting different content types. I was testing on Linux and content type was the same as I expected but in windows not.

**Comment by BaturevichNikita** [comment]
One of them is empty. I've tried an updated solution, but it is still not working.
[files.zip](https://github.com/dartwlad/nodejs-aws-be/files/5552137/files.zip)
image

**Comment by dartwlad** [comment]
@BaturevichNikita 

I'm able to upload your files on both windows and linux.
image
Maybe try to clear cache or smth...

**Review by petr150894 — APPROVED** [review]
Looks good! for me, uploading works correctly without any errors

**Pull request merged**
